### PR TITLE
figcaption same width as figures

### PR DESCRIPTION
**Pull request by mwernimont**
screen shot 2018-03-12 at 9 05 36 am
screen shot 2018-03-12 at 9 05 44 am

Hows this look @lindsaycarr ?

### CODE REVIEW

**Comment by mwernimont** [comment]
@lindsaycarr Thought about it and came up with a better solution. I put a div around the img and figcaption and gave it a max-width of 503px (the si=ze of the largest image we have in a figure tag.) That way instead of creating a hard-coded width for the figure caption text it dynamically adjusts per figure depending on its size, which gets a cleaner line up of the text and figure.

Also, I removed the .gdp-flex from the single figures, as the flex is for lining up 2 or more figures together on one line.

**Comment by lindsaycarr** [comment]
🎉 woo! looks great! The mobile fixes are completely separate, right?

**Comment by mwernimont** [comment]
Yep, haven't started on those since I have other sprint work and you said it wasn't a priority right now.

**Comment by mwernimont** [comment]
But let me know if that changes.

**Comment by lindsaycarr** [comment]
Not a priority, just wondering!

**Pull request merged**
