### PR TITLE
work beautifully with vizmake

### PR DESCRIPTION
**Pull request by aappling-usgs**
@lindsaycarr these should be the changes required to be in deep harmony with vizlab v0.2.2.9007 (using `vizmake()` to build the viz)

* git ignore remake files
* use style guide for header-section and footer-section
* use alwaysCurrent instead of vizlab:::fetchTimestamp.file for timestamps (same thing but clearer name, don't you think?)

### CODE REVIEW

**Comment by aappling-usgs** [comment]
(the corresponding vizlab PR is open at https://github.com/USGS-VIZLAB/vizlab/pull/323)

**Comment by lindsaycarr** [comment]
Wow, those are pretty simple changes! This was created after you sent that message about it not actually working after all in Slack, right? So it's good to merge? My timeline is a little mixed up.

**Comment by aappling-usgs** [comment]
Just wait on https://github.com/USGS-VIZLAB/vizlab/pull/323 is all; otherwise, yes, good to merge

**Comment by lindsaycarr** [comment]
So, "alwaysCurrent" ... sounds like it will just redo those steps each time even if there have been no recent changes? That's my problem now is that I feel like it just re-fetches every time.

**Comment by aappling-usgs** [comment]
`alwaysCurrent` is identical to `vizlab:::fetchTimestamp.file` but is exported. The function name reflects the currency of the data _source_, not the data as cached on your computer. And things don't rebuild if they're current. And tests on my computer indicate (finally!) that I've got timestamps working right for your use cases, such that they should (finally!) not refetch.

See the diagram at the top of https://github.com/USGS-VIZLAB/vizlab/pull/316. I'm going to call you to talk you through it.

**Pull request merged**
